### ISSUE TITLE
loop()について

### ISSUE THREAD

**Issue by nopnop2002** [bokunimowakaru/esp32c3#1]
おはようございます
有益なツールの公開、ありがとうございます。

この部分が気になったので、コメントさせていただきました。

https://github.com/bokunimowakaru/esp32c3/blob/master/benchmark/WhetStone/WhetStone.ino#L480

ご存知の様にardino for ESP32でビルドすると、以下のメイン関数が自動的に実行されます。

https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/main.cpp

loop()の前後でいくつかのコードが実行されます。

Setup()の中でwhetstone(0)を呼び出すと少し結果が変わるかもしれません。

**Comment by bokunimowakaru** [comment]
ありがとうございます。考えもしてませんでした。
確かに変わる可能性はあります。Setupに移動したうえで、さらに割り込みを禁止してみるとか、いくつか試してみようと思います。

**Comment by bokunimowakaru** [comment]
ESP32-C3にて確認してみましたが、変わりませんでした。

確認版は下記でコミットしてあります。
https://github.com/bokunimowakaru/esp32c3/blob/cdf837f93aaa003a5bcb462b90ac71a8625c88bb/benchmark/WhetStone/WhetStone.ino

（1msの違いは出ましたが、割り込みOFF時のほうが長かったので、時間数のカウント開始タイミングによるものと思います。）

ご指摘いただいた通り、微小な差が生じる可能性、今後、変化する可能性、他のMCUでは発生する可能性、あとWi-Fi動作時に差が発生することなども考えられますが、いまのところ、setup、loopの本来の使い方に合わせておこうと思います。
