### ISSUE TITLE
Whetstoneの結果

### ISSUE THREAD

**Issue by nopnop2002** [bokunimowakaru/esp32c3#2]
こんにちは

こちらで公開されているESP32のWhetstoneの結果ですが、Dhrystoneより高速でしょうか？

https://bokunimo.net/blog/esp/1491/

なんとなく、Whetstone(浮動小数点演算)の結果の方が、
Dhrystone(整数演算)より高速というのが違和感が有りコメントさせていただきました。

間違っていたら即座にクローズしてください。

**Comment by bokunimowakaru** [comment]
どうも、ありがとうございます。
ESP32-C3との比較に気をとられていました。
Whetstoneの方が高速というのは、あり得るのですが、30％も高速な結果が得られているのは、大いに違和感があります。コンパイル時のクロックの設定が異なっている気がします。とくにESP32のほうは2019年7月に測った結果でしたので、改めて測り直しておきます。

<html>
<body>


method|ESP32-C3 | ESP8266 | ESP32
-- | -- | -- | --
Whetstone (M WIPS) | 11.56 | 13.68 | 323.62
Dhrystone (DMIPS) | 172.35 | 96.26 | 250.82


</body>
</html>

**Comment by bokunimowakaru** [comment]
測り直しましたが、変わりませんでした。測定ミスは無さそうです。
また、前コメントのような過去の測定結果では無く、今回の公開時に測定した結果を記入していたようです。

[https://github.com/bokunimowakaru/esp32c3/blob/master/benchmark/results.txt](https://github.com/bokunimowakaru/esp32c3/blob/master/benchmark/results.txt)

演算内容や単位が異なるので、どちらが高く出てもおかしくはないですが、MPUと同じクロックかつ同じbit数のFPUを積んでいるので、整数演算も浮動小数演算も、似た値になると思います。
すぐではないですが、念のため、FPUを搭載したARMなどでも確認しておきます。
